---
name: Checks

on: [push]

#defines new job called 'test-lint'
jobs:
  #this is the ID which is required if you need to access this inside of GitHub actions
  test-lint:
    #The user-firendly name that you'll see in the Github Actions UI
   name: Test and Lint
   #The runner that we'll be running our job on. There are various different runners on the Github Actions Website
   runs-on: ubuntu-20.04
   #Steps are the different things that run for a job
   steps:
     #Name that we're giving to step which you'll see in the Github Actions UI
     - name: Login to Docker Hub
       #Uses allows us to use a premade action provided in the GitHub Action Repo
       uses: docker/login-action@v1
       #With the following parameters
       with:
         username: ${{ secrets.DOCKERHUB_USER }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
     - name: Checkout
       #Action provided by Github automatically, checks code out inside our GitHub Actions Job
       #We do this because by default the code is not checked out inside the job we're running
       uses: actions/checkout@v2
     - name: Test
       #This is the command that runs unit test on our project
       run: docker-compose run --rm app sh -c "python manage.py test"
     - name: Lint
       #This is the command that we use for
       run: docker-compose run --rm app sh -c "flake8"